ankitbro/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("chitrakatha.urls", namespace='chitrakatha')),
]

if settings:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chitrakatha/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name='chitrakatha'

urlpatterns = [
    url(r'^$', views.userpage, name='index'),
    url(r'^chitrakatha/$', views.mainpage, name='mainpage'),
    url(r'^chitrakatha/orders$', views.orders, name='orders'),
    #upload pages
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^upload/image$', views.image, name='image'),
    url(r'^upload/mainimage$', views.mainimage, name='mainimage'),
    url(r'^upload/blog$', views.blog, name='blog'),

    #images pages
    url(r'^images/$', views.images, name='images'),
    url(r'^images/(?P<id>\d+)/$', views.image_list, name='imagelist'),
    url(r'^images/(?P<id>\d+)/detail$', views.imagedetail, name='imagedetail'),
    url(r'^mainimage/(?P<id>\d+)/detail$', views.mainimagedetail, name='mainimagedetail'),

    #blog pages
    url(r'^blogs/$', views.blogs, name='blogs'),
    url(r'^blogs/(?P<id>\d+)/$', views.blog_list, name='bloglist'),
    url(r'^blogs/(?P<id>\d+)/detail$', views.blogdetail, name='blogdetail'),

    #login pages
    url(r'^login',views.sign_in.as_view(), name= 'login'),
    url(r'^logout',views.sign_out, name= 'logout'),

    #aboutpages
    url(r'^aboutme/$', views.aboutme, name='aboutme'),
    url(r'^chitrakatha/postview$', views.viewpage, name='viewpage'),

    #delete
    url(r'^chitrakatha/images/(?P<id>\d+)$', views.deleteimage, name='deleteimage'),
    url(r'^chitrakatha/images/(?P<id>\d+)/delete$', views.imagedelete, name='imagedelete'),
    url(r'^chitrakatha/blog/(?P<id>\d+)$', views.deleteblog, name='deleteblog'),
    url(r'^chitrakatha/blog/(?P<id>\d+)/delete$', views.blogdelete, name='blogdelete'),


    #update
    url(r'^chitrakatha/blog/(?P<id>\d+)/update$', views.updateblog, name='updateblog'),

    # url(r'^adminpage/postview/(?P<id>\d+)/$', views.blogdelete, name='blogupdate'),

    url(r'^thankyou/$', views.thankyou, name='thankyou'),
]

chitrakatha/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from datetime import timezone

#user table
class User(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1,on_delete=models.CASCADE,)

#mainimage
class MainImage(models.Model):
    place = models.CharField(max_length=120)
    shortdescription = models.CharField(max_length=80)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    image = models.FileField()
    published_Date = models.DateTimeField(auto_now=False, auto_now_add=True)

#image table
class AddImage(models.Model):
    place = models.CharField(max_length=120)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    mainimage = models.FileField()
    published_Date = models.DateTimeField(auto_now=False, auto_now_add=True)

    def get_absolute_url(self):
        return reverse("chitrakatha:imagelist", kwargs={"id":self.id})

    def get_url(self):
        return reverse("chitrakatha:imagelist", kwargs={"id":self.id})

#name of imagefilename
def get_image_filename(instance, filename):
    title = instance.post.place
    return "%s/%s" % (title, filename)

#multiple images linked to above addimage table
class Images(models.Model):
    post = models.ForeignKey(AddImage, default=None,on_delete=models.CASCADE,)
    image = models.FileField(upload_to=get_image_filename, verbose_name='Image', blank=True,)

#caption of image images
class ImageCaption(models.Model):
    postimage = models.ForeignKey(Images, default=None,on_delete=models.CASCADE,)
    image_caption = models.TextField()

    def get_url(self):
        return reverse("chitrakatha:imagedetail", kwargs={"id":self.id})

#Buyers table
class Buyers(models.Model):
    Name = models.CharField(max_length=120)
    Phone = models.CharField(max_length=10)
    image_id = models.FileField()

    def get_absolute_url(self):
        return reverse("chitrakatha:thankyou")

#blog table
class Blog(models.Model):
    place = models.CharField(max_length=120)
    Description = models.TextField()
    mainimage = models.FileField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    published_Date = models.DateTimeField(auto_now=False, auto_now_add=True)


    def get_url(self):
        return reverse("chitrakatha:bloglist", kwargs={"id":self.id})

#multiple images list to above blog table
class BlogImages(models.Model):
    post = models.ForeignKey(Blog, default=None,on_delete=models.CASCADE,)
    image = models.FileField(upload_to=get_image_filename, verbose_name='Image', blank=True,)

#captions of blog images
class Caption(models.Model):
    post = models.ForeignKey(BlogImages, default=None,on_delete=models.CASCADE,)
    image_caption = models.TextField()


    def get_url(self):
        return reverse("chitrakatha:blogdetail", kwargs={"id":self.id})

chitrakatha/forms.py
from django import forms

from .models import *

from django.contrib.auth.models import User

class ImagePostForm(forms.ModelForm):
    place = forms.CharField(max_length=120)
    mainimage = forms.FileField()

    class Meta:
        model = AddImage
        fields = ('place','mainimage', )

class MainImageForm(forms.ModelForm):
    place = forms.CharField(max_length=120)
    shortdescription = forms.CharField(max_length=80)
    image = forms.FileField()

    class Meta:
        model = MainImage
        fields = ('place','shortdescription','image', )


class ImageForm(forms.ModelForm):
    image = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    class Meta:
        model = Images
        fields = ('image', )

class OrderForm(forms.ModelForm):
    Name = forms.CharField(max_length=120)
    Phone = forms.CharField(max_length=10)
    class Meta:
        model = Buyers
        fields = ('Name', 'Phone', )

class BlogForm(forms.ModelForm):
    place = forms.CharField(max_length=120)
    Description = forms.CharField(widget=forms.Textarea)
    mainimage = forms.FileField()


    class Meta:
        model = Blog
        fields = ('place', 'Description','mainimage',)

class BlogImageForm(forms.ModelForm):
    image = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    class Meta:
        model = BlogImages
        fields = ('image', )

class CaptionForm(forms.ModelForm):
    image_caption = forms.CharField()
    class Meta:
        model = Caption
        fields = ('image_caption',)

class ImageCaptionForm(forms.ModelForm):
    image_caption = forms.CharField()
    class Meta:
        model = ImageCaption
        fields = ('image_caption',)

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control form-control-solid placeholder-no-fix',
        'required': 'true',
        'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-solid placeholder-no-fix',
        'required': 'true',
        'placeholder': 'Password', }))

    class Meta:
        fields = [
            "username",
            "password",
        ]

chitrakatha/views.py
#import necessary headers
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render
from django.forms import modelformset_factory
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View

from .models import *
from .forms import *

#upload display page
def upload(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    return render(request,"upload/upload.html")

def aboutme(request):
    return render(request,"mine/aboutme.html")
#mainpage
def userpage(request, id=None):

    queryset_list = Blog.objects.all()
    image_list = AddImage.objects.all()
    mainimage_list = MainImage.objects.all()

    paginator = Paginator(queryset_list, 3)
    page_req_var = "page"
    page = request.GET.get(page_req_var)
    queryset = paginator.get_page(page)

    pag = Paginator(image_list,3)
    page_request_var = "pge"
    page_var = request.GET.get(page_request_var)
    imageset = pag.get_page(page_var)

    context = {
        "image_list": imageset,
        "mainimage_list":mainimage_list,
        "page_req_var":page_req_var,
        "object_list":queryset,
        "page_request_var": page_request_var,
    }

    return render(request,"user/index.html", context)

#upload image page
def image(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form1 = ImagePostForm(request.POST or None, request.FILES or None)
    form2 = ImageForm(request.POST or None, request.FILES or None)
    files = request.FILES.getlist('image')
    if form2.is_valid() and form1.is_valid():
        post_form = form1.save(commit=False)
        post_form.save()
        for f in files:
            photo = Images(image=f,post=post_form,)
            photo.save()
        return HttpResponseRedirect(post_form.get_absolute_url())
    else:
        messages.error(request,"Not Created")
    context = {
        "form1":form1,
        "form2":form2,
    }
    return render(request, 'upload/uploadimage.html',context)

def mainimage(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = MainImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
		# messages.success(request, "<a href='#'>Item</a> saved",extra_tags='html_safe')
		# return HttpResponseRedirect(instance.get_absolute_url())
    context = {
			"form": form,
		}
    return render(request,"upload/mainimage.html",context)

#upload blog page
def blog(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form1 = BlogForm(request.POST or None, request.FILES or None)
    form2 = BlogImageForm(request.POST or None, request.FILES or None)
    files = request.FILES.getlist('image')
    if form2.is_valid() and form1.is_valid():
        post_form = form1.save(commit=False)
        post_form.save()
        for f in files:
            photo = BlogImages(image=f,post=post_form,)
            photo.save()
        return HttpResponseRedirect(post_form.get_url())
    else:
        messages.error(request,"Not Created")
    context = {
        "form1":form1,
        "form2":form2,
    }
    return render(request, 'upload/uploadblog.html',context)

#list of blogs
def blogs(request):
    queryset_list = Blog.objects.all()
    paginator = Paginator(queryset_list, 5)
    page_req_var = "page"
    page = request.GET.get(page_req_var)
    queryset = paginator.get_page(page)


    context = {
        "object_list": queryset,
        "page_req_var": page_req_var,
    }

    return render(request, 'user/blogs.html', context)

#list of images
def images(request):
    queryset_list = AddImage.objects.all()
    paginator = Paginator(queryset_list, 6)
    page_req_var = "page"
    page = request.GET.get(page_req_var)
    queryset = paginator.get_page(page)


    context = {
        "object_list": queryset,
        "page_req_var": page_req_var,
    }
    return render(request, 'user/images.html', context)

#image list by id
def image_list(request, id=None):
    instance_post = get_object_or_404(AddImage, id=id)
    all_images = Images.objects.filter(post=instance_post.id)
    queryset_list = ImageCaption.objects.all()

    context={
        "title": instance_post.place,
        "instance": instance_post,
        'image_list':all_images,
        "object_list": queryset_list,
    }
    return render(request, 'user/imagelist.html',context)

#blog list by id
def blog_list(request, id=None):
    instance_post = get_object_or_404(Blog, id=id)
    all_images = BlogImages.objects.filter(post=instance_post.id)
    queryset_list = Caption.objects.all()

    context={
        "title": instance_post.place,
        "instance": instance_post,
        'image_list':all_images,
        "object_list": queryset_list,
    }
    return render(request, 'user/bloglist.html',context)

#image individual detail
def imagedetail(request, id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        instance_image = get_object_or_404(Images, id=id)
        queryset_list = ImageCaption.objects.filter(postimage=instance_image.id).order_by('-id')
        form = OrderForm(request.POST or None, request.FILES or None)
        username = request.POST.get('Name')
        phonenumber = request.POST.get('Phone')

        if form.is_valid():
            order = Buyers(Name= username, Phone= phonenumber, image_id=instance_image.image)
            order.save()

            return HttpResponseRedirect(order.get_absolute_url())
        context={
            "instance": instance_image,
            "form":form,
            "object_list": queryset_list,
            "id" : id,
        }
        return render(request, 'user/imagedetail.html',context)
    instance_image = get_object_or_404(Images, id=id)
    queryset_list = ImageCaption.objects.filter(postimage=instance_image.id).order_by('-id')

    form = ImageCaptionForm(request.POST or None, request.FILES or None)
    caption = request.POST.get('image_caption')
    if form.is_valid():
        add_caption = ImageCaption(image_caption=caption, postimage=instance_image, id=instance_image.id)
        add_caption.save()

        return HttpResponseRedirect(add_caption.get_url())
    else:
        messages.error(request,"Not Created")
    context={
        "instance": instance_image,
        "form":form,
        "object_list": queryset_list,
    }
    return render(request, 'upload/addimagecaption.html',context)

def blogdetail(request, id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        instance_image = get_object_or_404(BlogImages, id=id)
        queryset_list = Caption.objects.filter(post=instance_image.id).order_by('-id')
        form = OrderForm(request.POST or None, request.FILES or None)
        username = request.POST.get('Name')
        phonenumber = request.POST.get('Phone')

        if form.is_valid():
            order = Buyers(Name= username, Phone= phonenumber, image_id=instance_image.image)
            order.save()

            return HttpResponseRedirect(order.get_absolute_url())
        context={
            "instance": instance_image,
            "form":form,
            "object_list": queryset_list,
            "id" : id,
        }
        return render(request, 'user/blogdetail.html',context)
    instance_image = get_object_or_404(BlogImages, id=id)
    queryset_list = Caption.objects.filter(post=instance_image.id).order_by('-id')

    form = CaptionForm(request.POST or None, request.FILES or None)
    caption = request.POST.get('image_caption')
    if form.is_valid():
        add_caption = Caption(image_caption=caption, post=instance_image, id=instance_image.id)
        add_caption.save()

        return HttpResponseRedirect(add_caption.get_url())
    else:
        messages.error(request,"Not Created")
    context={
        "instance": instance_image,
        "form":form,
        "object_list": queryset_list,
    }
    return render(request, 'upload/addimagecaption.html',context)



#admin sign in
class sign_in(View):
    def get(self, request):
        form = LoginForm()
        context = {
            'form': form,
        }
        return render(request, 'user/login.html', context)

    def post(self, request):
        form = LoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user and user.is_active:
                messages.success(request, "Logged In Successfully")
                login(request, user)
                return redirect('chitrakatha:upload')
        messages.warning(request, "Log In Failure")
        context = {
            'form': form,
        }
        return render(request, 'user/login.html', context)

#admin sign out
def sign_out(request):
    logout(request)
    return redirect('chitrakatha:login')

def mainpage(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    return render(request,"upload/upload.html")

def viewpage(request):
    if not request.user.is_superuser or not request.user.is_staff:
	       raise Http404
    image_list = AddImage.objects.all()
    blog_list = Blog.objects.all()

    paginator = Paginator(image_list, 4)
    page_req_var = "page"
    page = request.GET.get(page_req_var)
    queryset = paginator.get_page(page)

    pag = Paginator(blog_list, 4)
    page_request_var = "page"
    page = request.GET.get(page_request_var)

chitrakatha/templates/chitrakatha/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>{% block head_title %}Dip{% endblock head_title %}</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	{% load staticfiles %}
  <!-- Bootstrap CSS CDN -->

	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	 <!-- Fontawesome CSS CDN -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- Owl Carousel CSS -->
	<link rel="stylesheet" href="owl.carousel.min.css">
	<!-- Select2 -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
	<link rel="stylesheet" href='{%static "/css/base.css" %}'>
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body class="body" style="background-color:#EAEBEF">
  <div class = "top">
    <p class="classicfont">चित्र कथा (Chitra Katha)</p>
  </div>

	<nav class="navbar myblog">
			<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myblog-container" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
			</button>
			</div>

			<div class="collapse navbar-collapse" id="myblog-container">

			<ul class="nav navbar-nav">

					<li><a href="{% url 'chitrakatha:index' %}">User Page</a></li>
          <li><a href="{% url 'chitrakatha:upload' %}">Upload</a></li>
          <li><a href="{% url 'chitrakatha:viewpage' %}">View Post</a></li>
					<li><a href="{% url 'chitrakatha:orders' %}">Orders</a></li>
          <li><a href="{% url 'chitrakatha:logout' %}">Logout</a></li>

			</ul>


			</div><!-- /.navbar-collapse -->


	</nav>

<div>
	   {% block content %}
	   {% endblock %}
</div>
<div class="col-sm-12 foot">
<footer>
  <div class="row">
    <ul class="address">
        <li class="clearfix"><i class="fa fa-map-marker"></i> Jwagal, Kupondol</li>
        <li class="clearfix"><i class="fa fa-mobile"></i> 9841193789</li>
    </ul>

    <div class="social-contact">
    <b>Follow Me on</b>
    <div class="social-logo">
      <a href="#"><i class="fa fa-facebook-square" id="logofa"></i></a>
      <a href="#"><i class="fa fa-twitter" id="logofa"></i></a>
      <a href="#"><i class="fa fa-instagram" id="logofa"></i></a>
    </div>
  </div>
</div><br><br>
  <div class="me">
    <b>Developer:</b><br>
   	- Dipkiran Pradhan<br>
    - mail : 071bct516dip@pcampus.edu.np<br>
    <i class="fa fa-mobile"></i> 9860130803
    <div class="my-logo">
      <a href="https://github.com/Dipkiran"><i class="fa fa-github" id="logofa"></i></a>
      <a href="https://www.linkedin.com/in/dipkiran-pradhan-newar-88813b148/" id="logofa"><i class="fa fa-linkedin"></i></a>
    </div>

 </div>
</footer>
</div>

  <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
         <!-- Bootstrap Js CDN -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


        <!-- Owl Casousel JS -->

    </body>
</html>

chitrakatha/templates/chitrakatha/deleteblog.html
{% extends "chitrakatha/base.html" %}
{% load staticfiles %}
{% block content %}
<style>
    .captionimages img{
      height: 100%;
      width: 70%;
      margin-top: 2%;
      margin-left: 15%;
    }
    .captiontitle{
      padding: 1% 20%;
      font-size: 16px;
    }
    .blog-image-title{
      padding: 1% 15%;
      font-size: 28px;
      font-weight: 600;
    }
    .blog-image-desc{
      padding: 1% 15%;
      font-size: 16px;
    }
    #blog{
      background-color: #fff;
    }
</style>
<div class="col-sm-8 col-sm-offset-2" id="blog">
  <div class="blog-image-title"><b>{{ title | title }}</b></div><br>
  <div class="delete-question">Do you want to delete it?</div>
  <a href='{% url "chitrakatha:blogdelete" id=id %}'><button class="buttondelete"> Yes </button></a>
  <a href='{% url "chitrakatha:viewpage" %}'><button class="buttondelete"> No</button></a>
  <img src="/media/{{ instance.mainimage }}/" class="control-image"/>
  <div class="blog-image-desc"><p>{{ instance.Description | linebreaks}} </p></div>

    <div class="captionimages">

      {% for img in image_list %}


      <a href='{% url "chitrakatha:blogdetail" id=img.id %}'>
          <img src="/media/{{ img.image }}/" />
          </a>

          {% for cap in object_list %}
          <div class="captiontitle">
          {% if cap.id == img.id %}
          {{ cap.image_caption }}
          {% endif %}
        </div>
        {% endfor %}

      {% endfor %}

    </div>


</div>

{% endblock %}

chitrakatha/templates/chitrakatha/deleteimage.html
{% extends "chitrakatha/base.html" %}
{% load staticfiles %}

{% block content %}

<div class="col-sm-10 col-sm-offset-1" id="show-image">
  <div class="show-image-title"> <b>{{ title | title }}</b></div><br>
  <div class="delete-question">Do you want to delete it?</div>
  <a href='{% url "chitrakatha:imagedelete" id=id %}'><button class="buttondelete"> Yes </button></a>
  <a href='{% url "chitrakatha:viewpage" %}'><button class="buttondelete"> No</button></a>
  <div class="col-sm-12">
    <div class="show-imagescaption">

      {% for img in image_list %}

      <a href='{% url "chitrakatha:imagedetail" id=img.id %}'>
          <img src="/media/{{ img.image }}/" />
          </a>
          <div class="caption-title">
          {% for cap in object_list %}

          {% if cap.id == img.id %}
          {{ cap.image_caption }}
          {% endif %}


          {% endfor %}
            </div>
      {% endfor %}


    </div>

</div>

</div>

{% endblock %}

chitrakatha/templates/chitrakatha/updateblog.html
{% extends "chitrakatha/base.html" %}
{% load staticfiles %}
{% block content %}
<style>
    textarea{
      height: 350px;
      width: 900px;
    }
    #id_place{
      width: 20%;
    }
    form{
      width: 80%;
      margin-top: 2%;
    }
    #id_photo_caption1,#id_photo_caption2, #id_photo_caption3, #id_photo_caption4, #id_photo_caption5,#id_photo_caption6,
    #id_photo_caption7,#id_photo_caption8,#id_photo_caption9, #id_photo_caption10{
      width: 45%;
      margin-top: 3%;
    }

</style>
<div class="col-md-12 col-md-offset-2">
<form id="post_form" method="POST" action="" enctype="multipart/form-data">

    {% csrf_token %}
      {{ form1.as_p }}
      {{ form2.as_p }}


    <input type="submit" name="submit" value="Submit" />
</form>
</div>
{% endblock %}

chitrakatha/templates/chitrakatha/viewpage.html
{% extends "chitrakatha/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="col-sm-12" id="blog">
  <div class="title-image">
    <p>Image Album</p>
  </div>
{% for img in image_list %}
<div class="images-show">

  <div class="image-div">
      <a href="{{ img.get_url }}">
    <img src="/media/{{ img.mainimage }}/" alt="Los Angeles" >

    <div class="more-image">{{ img.place|title }} </div>
    </a>
    <a href='{% url "chitrakatha:deleteimage" id=img.id %}'><button class="delete-button"> delete </button></a>
  </div>


</div>
{% endfor %}
</div>
<div class="pagination">
      <span class="step-links">

          {% if image_list.has_previous %}
              <a href="?{page_req_var}=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo; first</a>
              <a href="?{{page_req_var}}={{ image_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ image_list.number }} of {{ image_list.paginator.num_pages }}.
          </span>

          {% if image_list.has_next %}
              <a href="?{{page_req_var}}={{ image_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
              <a href="?{{page_req_var}}={{ image_list.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">last &raquo;</a>
          {% endif %}
      </span>
  </div>


  <div class="title-blog">
    <p>Blog Post</p>
  </div>
            <div class="col-sm-12" id="blog">
            {% for blog in object_list %}


                  <div class="ablogs-post">
                      <div class="ablogs-text">
                        <div class="ablogs-title"> <strong>{{ blog.place|title }}</strong></div>
                        <img src="/media/{{ blog.mainimage }}/" />
                        <div class="ablogs-detail">{{ blog.Description|linebreaks|truncatechars:100 }}<a href='{{ blog.get_url }}'> Read More </a></div>
                      </div>
                      <a href='{% url "chitrakatha:deleteblog" id=blog.id %}'><button class="delete-button"> delete </button></a>
                        <a href='{% url "chitrakatha:updateblog" id=blog.id %}'><button class="delete-button"> Update </button></a>

                  </div>



           {% endfor %}
           </div>
           <div class="pagination">
                 <span class="step-links">

                     {% if object_list.has_previous %}
                         <a href="?{page_request_var}=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo; first</a>
                         <a href="?{{page_request_var}}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                     {% endif %}

                     <span class="current">
                         Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                     </span>

                     {% if object_list.has_next %}
                         <a href="?{{page_request_var}}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                         <a href="?{{page_request_var}}={{ object_list.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">last &raquo;</a>
                     {% endif %}
                 </span>
             </div>


{% endblock %}